/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authTermsConditionsRouteImport } from './routes/(auth)/terms-conditions'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authPrivacyPolicyRouteImport } from './routes/(auth)/privacy-policy'
import { Route as authLoginOtpRouteImport } from './routes/(auth)/login-otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authCommunityRouteImport } from './routes/(auth)/community'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appProfileIndexRouteImport } from './routes/(app)/profile/index'
import { Route as appNotificationsIndexRouteImport } from './routes/(app)/notifications/index'
import { Route as appNoticeBoardIndexRouteImport } from './routes/(app)/notice-board/index'
import { Route as appMyRequestsIndexRouteImport } from './routes/(app)/my-requests/index'
import { Route as appMembersIndexRouteImport } from './routes/(app)/members/index'
import { Route as appMarksheetsIndexRouteImport } from './routes/(app)/marksheets/index'
import { Route as appHelpIndexRouteImport } from './routes/(app)/help/index'
import { Route as appGlobalAdminIndexRouteImport } from './routes/(app)/global-admin/index'
import { Route as appGalleryIndexRouteImport } from './routes/(app)/gallery/index'
import { Route as appFindFamilyIndexRouteImport } from './routes/(app)/find-family/index'
import { Route as appFamilyTreeIndexRouteImport } from './routes/(app)/family-tree/index'
import { Route as appFamilyRequestsIndexRouteImport } from './routes/(app)/family-requests/index'
import { Route as appFamilyMembersIndexRouteImport } from './routes/(app)/family-members/index'
import { Route as appDonorsIndexRouteImport } from './routes/(app)/donors/index'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appCommitteeIndexRouteImport } from './routes/(app)/committee/index'
import { Route as appBusinessIndexRouteImport } from './routes/(app)/business/index'
import { Route as appAbroadMembersIndexRouteImport } from './routes/(app)/abroad-members/index'
import { Route as appAdminUserApprovalsIndexRouteImport } from './routes/(app)/admin/user-approvals/index'
import { Route as appAdminSuggestionsIndexRouteImport } from './routes/(app)/admin/suggestions/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authTermsConditionsRoute = authTermsConditionsRouteImport.update({
  id: '/(auth)/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authPrivacyPolicyRoute = authPrivacyPolicyRouteImport.update({
  id: '/(auth)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginOtpRoute = authLoginOtpRouteImport.update({
  id: '/(auth)/login-otp',
  path: '/login-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authCommunityRoute = authCommunityRouteImport.update({
  id: '/(auth)/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => appRouteRoute,
} as any)
const appNotificationsIndexRoute = appNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => appRouteRoute,
} as any)
const appNoticeBoardIndexRoute = appNoticeBoardIndexRouteImport.update({
  id: '/notice-board/',
  path: '/notice-board/',
  getParentRoute: () => appRouteRoute,
} as any)
const appMyRequestsIndexRoute = appMyRequestsIndexRouteImport.update({
  id: '/my-requests/',
  path: '/my-requests/',
  getParentRoute: () => appRouteRoute,
} as any)
const appMembersIndexRoute = appMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => appRouteRoute,
} as any)
const appMarksheetsIndexRoute = appMarksheetsIndexRouteImport.update({
  id: '/marksheets/',
  path: '/marksheets/',
  getParentRoute: () => appRouteRoute,
} as any)
const appHelpIndexRoute = appHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => appRouteRoute,
} as any)
const appGlobalAdminIndexRoute = appGlobalAdminIndexRouteImport.update({
  id: '/global-admin/',
  path: '/global-admin/',
  getParentRoute: () => appRouteRoute,
} as any)
const appGalleryIndexRoute = appGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => appRouteRoute,
} as any)
const appFindFamilyIndexRoute = appFindFamilyIndexRouteImport.update({
  id: '/find-family/',
  path: '/find-family/',
  getParentRoute: () => appRouteRoute,
} as any)
const appFamilyTreeIndexRoute = appFamilyTreeIndexRouteImport.update({
  id: '/family-tree/',
  path: '/family-tree/',
  getParentRoute: () => appRouteRoute,
} as any)
const appFamilyRequestsIndexRoute = appFamilyRequestsIndexRouteImport.update({
  id: '/family-requests/',
  path: '/family-requests/',
  getParentRoute: () => appRouteRoute,
} as any)
const appFamilyMembersIndexRoute = appFamilyMembersIndexRouteImport.update({
  id: '/family-members/',
  path: '/family-members/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDonorsIndexRoute = appDonorsIndexRouteImport.update({
  id: '/donors/',
  path: '/donors/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCommitteeIndexRoute = appCommitteeIndexRouteImport.update({
  id: '/committee/',
  path: '/committee/',
  getParentRoute: () => appRouteRoute,
} as any)
const appBusinessIndexRoute = appBusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAbroadMembersIndexRoute = appAbroadMembersIndexRouteImport.update({
  id: '/abroad-members/',
  path: '/abroad-members/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminUserApprovalsIndexRoute =
  appAdminUserApprovalsIndexRouteImport.update({
    id: '/admin/user-approvals/',
    path: '/admin/user-approvals/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAdminSuggestionsIndexRoute =
  appAdminSuggestionsIndexRouteImport.update({
    id: '/admin/suggestions/',
    path: '/admin/suggestions/',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof authCommunityRoute
  '/login': typeof authLoginRoute
  '/login-otp': typeof authLoginOtpRoute
  '/privacy-policy': typeof authPrivacyPolicyRoute
  '/register': typeof authRegisterRoute
  '/terms-conditions': typeof authTermsConditionsRoute
  '/abroad-members/': typeof appAbroadMembersIndexRoute
  '/business/': typeof appBusinessIndexRoute
  '/committee/': typeof appCommitteeIndexRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/donors/': typeof appDonorsIndexRoute
  '/family-members/': typeof appFamilyMembersIndexRoute
  '/family-requests/': typeof appFamilyRequestsIndexRoute
  '/family-tree/': typeof appFamilyTreeIndexRoute
  '/find-family/': typeof appFindFamilyIndexRoute
  '/gallery/': typeof appGalleryIndexRoute
  '/global-admin/': typeof appGlobalAdminIndexRoute
  '/help/': typeof appHelpIndexRoute
  '/marksheets/': typeof appMarksheetsIndexRoute
  '/members/': typeof appMembersIndexRoute
  '/my-requests/': typeof appMyRequestsIndexRoute
  '/notice-board/': typeof appNoticeBoardIndexRoute
  '/notifications/': typeof appNotificationsIndexRoute
  '/profile/': typeof appProfileIndexRoute
  '/settings/': typeof appSettingsIndexRoute
  '/admin/suggestions/': typeof appAdminSuggestionsIndexRoute
  '/admin/user-approvals/': typeof appAdminUserApprovalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof authCommunityRoute
  '/login': typeof authLoginRoute
  '/login-otp': typeof authLoginOtpRoute
  '/privacy-policy': typeof authPrivacyPolicyRoute
  '/register': typeof authRegisterRoute
  '/terms-conditions': typeof authTermsConditionsRoute
  '/abroad-members': typeof appAbroadMembersIndexRoute
  '/business': typeof appBusinessIndexRoute
  '/committee': typeof appCommitteeIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/donors': typeof appDonorsIndexRoute
  '/family-members': typeof appFamilyMembersIndexRoute
  '/family-requests': typeof appFamilyRequestsIndexRoute
  '/family-tree': typeof appFamilyTreeIndexRoute
  '/find-family': typeof appFindFamilyIndexRoute
  '/gallery': typeof appGalleryIndexRoute
  '/global-admin': typeof appGlobalAdminIndexRoute
  '/help': typeof appHelpIndexRoute
  '/marksheets': typeof appMarksheetsIndexRoute
  '/members': typeof appMembersIndexRoute
  '/my-requests': typeof appMyRequestsIndexRoute
  '/notice-board': typeof appNoticeBoardIndexRoute
  '/notifications': typeof appNotificationsIndexRoute
  '/profile': typeof appProfileIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/admin/suggestions': typeof appAdminSuggestionsIndexRoute
  '/admin/user-approvals': typeof appAdminUserApprovalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)/community': typeof authCommunityRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/login-otp': typeof authLoginOtpRoute
  '/(auth)/privacy-policy': typeof authPrivacyPolicyRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/terms-conditions': typeof authTermsConditionsRoute
  '/(app)/abroad-members/': typeof appAbroadMembersIndexRoute
  '/(app)/business/': typeof appBusinessIndexRoute
  '/(app)/committee/': typeof appCommitteeIndexRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/donors/': typeof appDonorsIndexRoute
  '/(app)/family-members/': typeof appFamilyMembersIndexRoute
  '/(app)/family-requests/': typeof appFamilyRequestsIndexRoute
  '/(app)/family-tree/': typeof appFamilyTreeIndexRoute
  '/(app)/find-family/': typeof appFindFamilyIndexRoute
  '/(app)/gallery/': typeof appGalleryIndexRoute
  '/(app)/global-admin/': typeof appGlobalAdminIndexRoute
  '/(app)/help/': typeof appHelpIndexRoute
  '/(app)/marksheets/': typeof appMarksheetsIndexRoute
  '/(app)/members/': typeof appMembersIndexRoute
  '/(app)/my-requests/': typeof appMyRequestsIndexRoute
  '/(app)/notice-board/': typeof appNoticeBoardIndexRoute
  '/(app)/notifications/': typeof appNotificationsIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(app)/admin/suggestions/': typeof appAdminSuggestionsIndexRoute
  '/(app)/admin/user-approvals/': typeof appAdminUserApprovalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/login'
    | '/login-otp'
    | '/privacy-policy'
    | '/register'
    | '/terms-conditions'
    | '/abroad-members/'
    | '/business/'
    | '/committee/'
    | '/dashboard/'
    | '/donors/'
    | '/family-members/'
    | '/family-requests/'
    | '/family-tree/'
    | '/find-family/'
    | '/gallery/'
    | '/global-admin/'
    | '/help/'
    | '/marksheets/'
    | '/members/'
    | '/my-requests/'
    | '/notice-board/'
    | '/notifications/'
    | '/profile/'
    | '/settings/'
    | '/admin/suggestions/'
    | '/admin/user-approvals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/login'
    | '/login-otp'
    | '/privacy-policy'
    | '/register'
    | '/terms-conditions'
    | '/abroad-members'
    | '/business'
    | '/committee'
    | '/dashboard'
    | '/donors'
    | '/family-members'
    | '/family-requests'
    | '/family-tree'
    | '/find-family'
    | '/gallery'
    | '/global-admin'
    | '/help'
    | '/marksheets'
    | '/members'
    | '/my-requests'
    | '/notice-board'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/admin/suggestions'
    | '/admin/user-approvals'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)/community'
    | '/(auth)/login'
    | '/(auth)/login-otp'
    | '/(auth)/privacy-policy'
    | '/(auth)/register'
    | '/(auth)/terms-conditions'
    | '/(app)/abroad-members/'
    | '/(app)/business/'
    | '/(app)/committee/'
    | '/(app)/dashboard/'
    | '/(app)/donors/'
    | '/(app)/family-members/'
    | '/(app)/family-requests/'
    | '/(app)/family-tree/'
    | '/(app)/find-family/'
    | '/(app)/gallery/'
    | '/(app)/global-admin/'
    | '/(app)/help/'
    | '/(app)/marksheets/'
    | '/(app)/members/'
    | '/(app)/my-requests/'
    | '/(app)/notice-board/'
    | '/(app)/notifications/'
    | '/(app)/profile/'
    | '/(app)/settings/'
    | '/(app)/admin/suggestions/'
    | '/(app)/admin/user-approvals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authCommunityRoute: typeof authCommunityRoute
  authLoginRoute: typeof authLoginRoute
  authLoginOtpRoute: typeof authLoginOtpRoute
  authPrivacyPolicyRoute: typeof authPrivacyPolicyRoute
  authRegisterRoute: typeof authRegisterRoute
  authTermsConditionsRoute: typeof authTermsConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/terms-conditions': {
      id: '/(auth)/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof authTermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/privacy-policy': {
      id: '/(auth)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof authPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login-otp': {
      id: '/(auth)/login-otp'
      path: '/login-otp'
      fullPath: '/login-otp'
      preLoaderRoute: typeof authLoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/community': {
      id: '/(auth)/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof authCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/notifications/': {
      id: '/(app)/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof appNotificationsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/notice-board/': {
      id: '/(app)/notice-board/'
      path: '/notice-board'
      fullPath: '/notice-board/'
      preLoaderRoute: typeof appNoticeBoardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/my-requests/': {
      id: '/(app)/my-requests/'
      path: '/my-requests'
      fullPath: '/my-requests/'
      preLoaderRoute: typeof appMyRequestsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/members/': {
      id: '/(app)/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof appMembersIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/marksheets/': {
      id: '/(app)/marksheets/'
      path: '/marksheets'
      fullPath: '/marksheets/'
      preLoaderRoute: typeof appMarksheetsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/help/': {
      id: '/(app)/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof appHelpIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/global-admin/': {
      id: '/(app)/global-admin/'
      path: '/global-admin'
      fullPath: '/global-admin/'
      preLoaderRoute: typeof appGlobalAdminIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/gallery/': {
      id: '/(app)/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof appGalleryIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/find-family/': {
      id: '/(app)/find-family/'
      path: '/find-family'
      fullPath: '/find-family/'
      preLoaderRoute: typeof appFindFamilyIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/family-tree/': {
      id: '/(app)/family-tree/'
      path: '/family-tree'
      fullPath: '/family-tree/'
      preLoaderRoute: typeof appFamilyTreeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/family-requests/': {
      id: '/(app)/family-requests/'
      path: '/family-requests'
      fullPath: '/family-requests/'
      preLoaderRoute: typeof appFamilyRequestsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/family-members/': {
      id: '/(app)/family-members/'
      path: '/family-members'
      fullPath: '/family-members/'
      preLoaderRoute: typeof appFamilyMembersIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/donors/': {
      id: '/(app)/donors/'
      path: '/donors'
      fullPath: '/donors/'
      preLoaderRoute: typeof appDonorsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/committee/': {
      id: '/(app)/committee/'
      path: '/committee'
      fullPath: '/committee/'
      preLoaderRoute: typeof appCommitteeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/business/': {
      id: '/(app)/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof appBusinessIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/abroad-members/': {
      id: '/(app)/abroad-members/'
      path: '/abroad-members'
      fullPath: '/abroad-members/'
      preLoaderRoute: typeof appAbroadMembersIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin/user-approvals/': {
      id: '/(app)/admin/user-approvals/'
      path: '/admin/user-approvals'
      fullPath: '/admin/user-approvals/'
      preLoaderRoute: typeof appAdminUserApprovalsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin/suggestions/': {
      id: '/(app)/admin/suggestions/'
      path: '/admin/suggestions'
      fullPath: '/admin/suggestions/'
      preLoaderRoute: typeof appAdminSuggestionsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appAbroadMembersIndexRoute: typeof appAbroadMembersIndexRoute
  appBusinessIndexRoute: typeof appBusinessIndexRoute
  appCommitteeIndexRoute: typeof appCommitteeIndexRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appDonorsIndexRoute: typeof appDonorsIndexRoute
  appFamilyMembersIndexRoute: typeof appFamilyMembersIndexRoute
  appFamilyRequestsIndexRoute: typeof appFamilyRequestsIndexRoute
  appFamilyTreeIndexRoute: typeof appFamilyTreeIndexRoute
  appFindFamilyIndexRoute: typeof appFindFamilyIndexRoute
  appGalleryIndexRoute: typeof appGalleryIndexRoute
  appGlobalAdminIndexRoute: typeof appGlobalAdminIndexRoute
  appHelpIndexRoute: typeof appHelpIndexRoute
  appMarksheetsIndexRoute: typeof appMarksheetsIndexRoute
  appMembersIndexRoute: typeof appMembersIndexRoute
  appMyRequestsIndexRoute: typeof appMyRequestsIndexRoute
  appNoticeBoardIndexRoute: typeof appNoticeBoardIndexRoute
  appNotificationsIndexRoute: typeof appNotificationsIndexRoute
  appProfileIndexRoute: typeof appProfileIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
  appAdminSuggestionsIndexRoute: typeof appAdminSuggestionsIndexRoute
  appAdminUserApprovalsIndexRoute: typeof appAdminUserApprovalsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAbroadMembersIndexRoute: appAbroadMembersIndexRoute,
  appBusinessIndexRoute: appBusinessIndexRoute,
  appCommitteeIndexRoute: appCommitteeIndexRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  appDonorsIndexRoute: appDonorsIndexRoute,
  appFamilyMembersIndexRoute: appFamilyMembersIndexRoute,
  appFamilyRequestsIndexRoute: appFamilyRequestsIndexRoute,
  appFamilyTreeIndexRoute: appFamilyTreeIndexRoute,
  appFindFamilyIndexRoute: appFindFamilyIndexRoute,
  appGalleryIndexRoute: appGalleryIndexRoute,
  appGlobalAdminIndexRoute: appGlobalAdminIndexRoute,
  appHelpIndexRoute: appHelpIndexRoute,
  appMarksheetsIndexRoute: appMarksheetsIndexRoute,
  appMembersIndexRoute: appMembersIndexRoute,
  appMyRequestsIndexRoute: appMyRequestsIndexRoute,
  appNoticeBoardIndexRoute: appNoticeBoardIndexRoute,
  appNotificationsIndexRoute: appNotificationsIndexRoute,
  appProfileIndexRoute: appProfileIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
  appAdminSuggestionsIndexRoute: appAdminSuggestionsIndexRoute,
  appAdminUserApprovalsIndexRoute: appAdminUserApprovalsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authCommunityRoute: authCommunityRoute,
  authLoginRoute: authLoginRoute,
  authLoginOtpRoute: authLoginOtpRoute,
  authPrivacyPolicyRoute: authPrivacyPolicyRoute,
  authRegisterRoute: authRegisterRoute,
  authTermsConditionsRoute: authTermsConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
